### ISSUE TITLE
Add support for content scripts

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/web-extension-starter#12]
Feature Request

**Comment by jgornick** [comment]
Great project!

I was wondering if this is something that can be done manually without having to implement a templated solution? I'm looking to support content scripts so that I can inject a script into a page.

Any help would be greatly appreciated!

Thanks!

**Comment by abhijithvijayan** [comment]
Let me look onto that

**Comment by jgornick** [comment]
I suppose one could inject programmatically: https://developer.chrome.com/extensions/content_scripts#programmatic

**Comment by abhijithvijayan** [comment]
I guess, adding an entry to webpack config file and then updating the manifest file would do it nice and smooth.

```
"content_scripts": [ { "matches": ["http://*.nytimes.com/*"], "css": ["myStyles.css"], "js": ["contentScript.js"] } ],

```

**Comment by jgornick** [comment]
I'll keep you posted. It's getting late here, so might have to dive in tomorrow. Thank you so much!

**Comment by abhijithvijayan** [comment]
I will try to add a demo with content scripts.

**Comment by abhijithvijayan** [comment]
I just added a sample content script file to this starter as well.

**Comment by jgornick** [comment]
Awesome! Works @abhijithvijayan, thank you!

**Comment by abhijithvijayan** [comment]
@jgornick Good to hear. :smiley:
