### ISSUE TITLE
what's eslint-config-onepass?

### ISSUE THREAD

**Issue by zicjin** [abhijithvijayan/web-extension-starter#13]
I can't understand its role in this project. Is it possible to use a general solution?

**Comment by abhijithvijayan** [comment]
`eslint-config-onepass` is my custom set of rules for Eslint and Prettier.

If you don't wanna use my styles and rules, feel free to remove all the linting dev dependencies and set up the configuration all by yourself.

**Comment by abhijithvijayan** [comment]
You can view all rules and also the instructions to remove `eslint-config-onepass` and its `devDependencies` at https://github.com/onepassapp/eslint-config-onepass

**Comment by zicjin** [comment]
The significance of the starter project is to minimize the user's customization work with a common solution. And I see that some eslint config|plugins are already defined in package.json. Why not use them directly?
```json
{
  "extends": [
    "airbnb",
    "plugin:react/recommended",
    "prettier"
  ],
  "plugins": [
    "react-hooks",
    "jsx-a11y",
    "import",
    "prettier"
  ],
  "env": {
    "browser": true,
    "webextensions": true
  },
  "rules": {
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn"
  }
}
```

**Comment by abhijithvijayan** [comment]
@zicjin Anyone using this starter could've overridden or even removed whole configuration and added their own custom rules which they are used to.

I didn't want to write all the configuration manually for this repo as I use the package in all other projects regularly.

If you think adding the user customizable(which still is now) to the single configuration, feel free to submit a PR and I will merge it.
