### ISSUE TITLE
master branch: switch to npm, source map error appears

### ISSUE THREAD

**Issue by hhaoao** [abhijithvijayan/web-extension-starter#21]
@abhijithvijayan I follow your prompt to delete the relevant files and modify the package.json file:
```
"build": "npm run build:chrome && npm run build:firefox && npm run build:opera"
```
Follow readme.md, run:
```
npm run dev:firefox
```

But I'm having a small problem,if you know how to fix it please let me know. (I don't know if I'm going to encounter it with yarn),`Source map error` problems have kept me at bay.

```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://f3e071f8-a623-4e01-9f41-8c1d7afeec8e/js/contentScript.bundle.js
Source Map URL: browser-polyfill.js.map
```

I didn't modify `travis.yml` file because I didn't use 'travis-ci'.

**Comment by abhijithvijayan** [comment]
You are using the non typescript version right?

**Comment by hhaoao** [comment]
Yes, non typescript version, here's my fork master branch's repository.
https://github.com/hhaoao/web-extension-starter.git

**Comment by abhijithvijayan** [comment]
I will look into it tonight

**Comment by hhaoao** [comment]
I installed yarn, i saw the error message, `web-extension-starter`, `wext-manifest` asked the `node` version >=8 <=12. If you haven't solved the problem of project compatibility with npm, I think you should upgrade to Yarn v2,node upgrade with other packages to the latest first, otherwise you might waste more time.

**Comment by abhijithvijayan** [comment]
Sorry, I was about to look into it.

The berry release of yarn has caused a lot of issues to many people.

Yarn 2 requires Node.js 10 or above.

If you are planning to use yarn(which I recommend) have node.js 10 or 12 installed(through nvm if on linux)

I will soon drop support for node.js 8

**Comment by abhijithvijayan** [comment]
I have made both the branches to limit only using node.js 10 and above.
Yarn works for both v1 & v2 installed on machine(it uses yarn v1 in `.yarn/releases` by default.

Also, later I can migrate to `yarn 2 berry` with `node_modules` installs enabled or disabled(`PnP-loose` mode)

even with this breaking change([read more](https://github.com/yarnpkg/berry/issues/766#issuecomment-580658470)) `yarn` is far better than `npm` itself

I'd recommend you giving `yarn` a try. If you still need `npm branch`, please let me know.

**Comment by hhaoao** [comment]
Thank, I'm going to switch to yarn v1 and I'll continue to build this project with npm, which should be a compatibility issue caused by some packages, which shouldn't be very difficult.

**Comment by abhijithvijayan** [comment]
Just delete 

`.yarn`, `yarn.lock`, `.yarnrc.yml`, `node_modules`

Run `npm install`

Update scripts with npm

This should work by default.
