### ISSUE TITLE
What is short_name ?

### ISSUE THREAD

**Issue by subins2000** [abhijithvijayan/web-extension-starter#25]
In `manifest/index.js`, there's the field `short_name`. What is it for ?

**Comment by abhijithvijayan** [comment]
It is used when the name is too long 

You can checkout the documentation [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/short_name)

Also, please do note that, the underlying package `wext-manifest` requires a js file to generate the manifest files(for now)

This will be changed in the upcoming version for which it is planned to be released as a webpack loader (under `wext-manifest-loader`) which resolves the issue of keeping the `manifest.json/index.js`. Instead it can be kept as `manifest.json` with browser specific contents which will be autobundled correctly.

**Comment by abhijithvijayan** [comment]
The migration will be as simple as
- removing and installing new loader package
- move contents to manifest.json
- deleting js file
- replacing entry in webpack config

**Comment by abhijithvijayan** [comment]
@subins2000 I will be closing this for now.

Feel free to reopen if any such questions are raised.

Thanks.

**Comment by subins2000** [comment]
Got it. Thank you for the quick reply !
