### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by princesust** [abhijithvijayan/web-extension-starter#30]
If there are multiple extension using this boilerplate. Then if I put `npm run dev:chrome` then all the extension reloaded.

**Comment by abhijithvijayan** [comment]
The extension reloader works by injecting a script and running a server for auto reloading.

To not reload all the extensions using the same boilerplate, I suggest changing port of extension reloader to a different one per extension.

**Comment by abhijithvijayan** [comment]
Did it work?

**Comment by abhijithvijayan** [comment]
Closing for now. Feel free to reopen this if issue still persists.
