### ISSUE TITLE
Expose environmental variables from .env

### ISSUE THREAD

**Issue by MatteoGioioso** [abhijithvijayan/web-extension-starter#32]
I have tried the classic `.env` with `REACT_APP` prefix, but it does not work, I guess that is only for `react-script`.
Does this package it support something similar?
Thanks

**Comment by MatteoGioioso** [comment]
I have found an easy way to handle it with `dotenv`

```
const dotenv = require("dotenv");

const env = dotenv.config().parsed;
const envKeys = Object.keys(env).reduce((prev, next) => {
  prev[`process.env.${next}`] = JSON.stringify(env[next]);
  return prev;
}, {});

```
and then in plugins

```
 plugins:[
    new webpack.DefinePlugin(envKeys)
  ]
```

**Comment by abhijithvijayan** [comment]
@MatteoGioioso This only works with `create-react-app` running with `react-scripts`

**Comment by abhijithvijayan** [comment]
@MatteoGioioso I dont think this is necessary.

Official webpack docs suggests to use `dotenv-webpack` plugin

Try using that instead 

https://webpack.js.org/plugins/environment-plugin/#dotenvplugin

**Comment by abhijithvijayan** [comment]
Currently, `EnvironmentPlugin` maps the `NODE_ENV` and `TARGET_BROWSER` variables passed through the scripts to `process.env`

It performs the same like `DefinePlugin` but is specifically for `process.env`

I thinks it's best to use the `EnvironmentPlugin` for these two variables and use `dotenv-webpack` plugin for any other variables.

**Comment by MatteoGioioso** [comment]
@abhijithvijayan Unfortunately that approach did not work for me.

**Comment by abhijithvijayan** [comment]
Maybe the .env path is wrong.

I will set this up later and push the changes.

**Comment by MatteoGioioso** [comment]
@abhijithvijayan wait, your package works fine, I just needed to add `dotenv` to pass my environmental variables for react

**Comment by abhijithvijayan** [comment]
Anyways, I will set this up.

**Comment by robindijkhof** [comment]
any update on this?

**Comment by abhijithvijayan** [comment]
@robindijkhof 

Will look into your PR later.

**Comment by abhijithvijayan** [comment]
Since this is a simple addition to the starter, if needed, anyone can set it up by referring PR #60
