### ISSUE TITLE
Selenium/WebDriver tests

### ISSUE THREAD

**Issue by slhck** [abhijithvijayan/web-extension-starter#34]
I have been trying to use your code base to set up a wrapper with Jest and Selenium-Webdriver in order to install the extension in Chrome and Firefox.

In case you would like to add this to your code, please find some starting points here:

https://github.com/slhck/web-extension-selenium-test

Particularly see the `test` scripts in `package.json` as well as the files in `test/integration`.

I've run into a [bug with Firefox ](https://github.com/SeleniumHQ/selenium/issues/8285), where the XPI is not installed, but for Chrome it works fine.

I am not opening a PR at this stage because it is far from complete, but I'm leaving it here as a pointer.

**Comment by abhijithvijayan** [comment]
Is it necessary to test the extension within the browser?

The idea seems to interesting as even if all sorts of tests are successful, production errors(user system browser specific) errors usually can happen.

Do submit a PR once the wrapper is functional.

Thanks.

**Comment by abhijithvijayan** [comment]
Closing for now.

**Comment by slhck** [comment]
Whoops, yeah, sorry for not following up with you on this. We have a solution and I may be able to port it back to this repo. Will file a PR if I get to it.

**Comment by abhijithvijayan** [comment]
Well if you get it working and ready to put a PR, I will create a new branch with that.

This is to keep the other 3 main branches as minimal as possible.
