### ISSUE TITLE
Feat: react + javascript branch

### ISSUE THREAD

**Issue by princesust** [abhijithvijayan/web-extension-starter#37]
some people think typescript is extra overhead when you have a time constraint.

**Comment by abhijithvijayan** [comment]
It doesn't require much effort.

**Comment by princesust** [comment]
I already did it for myself. But a warning shows for core js. I resolved that issue by install core-js and make a change in .babelrc file. Not sure is that the correct procedure.

**Comment by abhijithvijayan** [comment]
I saw the core-js warning, didnt want to add another dependency and handle its updates and stuff.

It is a dependency of another dependency, unless the core team of the dependency that requires core-js changes it, we dont have to do anything and can ignore the warning.

Also, I will take care of the new branch, doesnt require much effort.

**Comment by princesust** [comment]
Ok, I will push a new branch.

**Comment by abhijithvijayan** [comment]
Its fine.

**Comment by abhijithvijayan** [comment]
I am half way done.

**Comment by abhijithvijayan** [comment]
@princesust Checkout https://github.com/abhijithvijayan/web-extension-starter/tree/react-javascript branch

**Comment by abhijithvijayan** [comment]
Also pushed a fix to disable that `core-js` version warning
