### ISSUE TITLE
Not able to import images

### ISSUE THREAD

**Issue by Akshay090** [abhijithvijayan/web-extension-starter#40]
webpack gives error for importing images in react

**Comment by abhijithvijayan** [comment]
You don't have to import image assets, webpack automatically copies `source/assets` folder to `build` directory under `assets` folder.

Copy the image to `source/assets` folder and use it 
```
<img src="assets/logo.jpg" />
```

**Comment by Akshay090** [comment]
oh I didn't knew that. I don't think there would be any special benefit to import image as we typically do in normal react app. Your method of doing it is good.

**Comment by abhijithvijayan** [comment]
create-react-app has loaders to handle the asset imports.

I didnt want to add more loaders to the boilerplate as webextensions usually do not require much of images.
