### ISSUE TITLE
All colors are inverted?

### ISSUE THREAD

**Issue by AdityaAnand1** [abhijithvijayan/web-extension-starter#45]
![image](https://user-images.githubusercontent.com/13274079/88268860-b76fdb80-ccf0-11ea-9568-5ee6da97da1d.png)

For some reason, all website colors are inverted whenever I activate this boilerplate extension.

Just git pulled and loaded into the latest chrome, no other changes. It goes back to normal when I remove/disable this specific extension and I can't find any styles that lead to this. There's nothing else to attribute this to except this extension being loaded.

What's going on? Any ideas?

**Comment by abhijithvijayan** [comment]
The sample code(in ContentScripts) invert the color.

It was done for the demo, but I guess it causes more ambiguity.

**Comment by AdityaAnand1** [comment]
Ahh! Just saw it. Yeah, that was a little jarring. Hehe, I think the icon appearing + popup/options etc. is enough evidence that the extension boilerplate works.

Anyone wanting to do more will inevitably stumble to official extension docs in which case they can figure out by themselves what contentscript can be used for.

I think this should be removed. Or commented.

**Comment by abhijithvijayan** [comment]
Nice catch @AdityaAnand1 

I have removed the line from all 3 branches.
