### ISSUE TITLE
README typo Taylored -> Tailored

### ISSUE THREAD

**Issue by niftylettuce** [abhijithvijayan/web-extension-starter#46]

**Comment by abhijithvijayan** [comment]
Switch to the branch where there is this typo, fix the typo, submit a PR

**Comment by niftylettuce** [comment]
It's on your default branch.

**Comment by abhijithvijayan** [comment]
Please submit a PR

**Comment by niftylettuce** [comment]
It's in the master branch, and best of luck with this project
