### ISSUE TITLE
Can we show this extension like a sidebar instead? 

### ISSUE THREAD

**Issue by anubhavmalik** [abhijithvijayan/web-extension-starter#48]
I tried injecting code via content script but didn't work

**Comment by abhijithvijayan** [comment]
It seems possible

Checkout https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Sidebars

**Comment by anubhavmalik** [comment]
I will re-open this when I am able to try this out. For now I am closing this issue since I am not able to pursue this further.

**Comment by anubhavmalik** [comment]
Thank you for the reply @abhijithvijayan ...
I will re-open this when I am able to try this out. For now I am closing this issue since I am not able to pursue this further.
