### ISSUE TITLE
[FEAT] Support for Safari Browsers

### ISSUE THREAD

**Issue by anaclumos** [abhijithvijayan/web-extension-starter#49]
I have found previous issues (#9 and #11) that Safari uses its proprietary extension format, and web-extension-starter for Safari will not be worked on. I am curious about an updated plan since Safari supports WebExtension from Safari 14. Will there be a Safari branch?

References:
* [https://developer.apple.com/safari/extensions/](https://developer.apple.com/safari/extensions/)
* [https://developer.apple.com/documentation/safariservices/safari_web_extensions](https://developer.apple.com/documentation/safariservices/safari_web_extensions)
* [https://hacks.mozilla.org/2020/06/welcoming-safari-to-the-webextensions-community/](https://hacks.mozilla.org/2020/06/welcoming-safari-to-the-webextensions-community/)

**Comment by abhijithvijayan** [comment]
I dont own a mac. So I cant really test anything on it.

**Comment by abhijithvijayan** [comment]
But if it does support webextensions, it wont be that hard for the starter to support it

**Comment by abhijithvijayan** [comment]
Can test this out.

**Comment by VladSez** [comment]
Maybe this thread can be helpful: https://github.com/sindresorhus/refined-github/issues/14
Also this: https://developer.apple.com/videos/play/wwdc2021/10104/

**Comment by abhijithvijayan** [comment]
Thanks

**Comment by wirtzdan** [comment]
Would be super awesome! 👏

**Comment by abhijithvijayan** [comment]
Will work on this in some spare time that I get.

**Comment by wirtzdan** [comment]
Thanks! 🙏

**Comment by fregante** [comment]
I plan on extracting the code I wrote for Refined GitHub (mentioned earlier) into its own module and make Safari support easier for non-Xcode developer. If you wait… a bit longer… I might get to it.

**Comment by abhijithvijayan** [comment]
Nice @fregante

**Comment by abhijithvijayan** [comment]
https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

**Comment by MerrickClark** [comment]
@abhijithvijayan / those contributing (or considering) towards Safari support:
I'm working on an existing project utilizing this awesome starter kit; PS great work @abhijithvijayan!

I'm confident I can get a solid monetary donation towards adding Safari support if there's willingness on the contributors side of things. I've been trying to port what I have working to Xcode and I'm hitting wall after wall- some probably unrelated to this project but simply because my Xcode/apple dev experience is nil.

I'm under the impression there's still an unknown amount of work bringing Safari support into this project and I've personally discovered there's limited community resources about Safari JS based web extension dev.

Thoughts?

**Comment by fregante** [comment]
What problem are you encountering? I haven't had time to extract the code as I was hoping, but Apple's conversion tool should do most of the work of loading the extension in the browser.

**Comment by abhijithvijayan** [comment]
The underlying support @fregante did can be seen on 
- https://github.com/refined-github/refined-github/pull/3677
- https://github.com/refined-github/refined-github/issues/3686#issue-728911931
- https://github.com/refined-github/refined-github/pull/4787

Apple Conversion Tool ref: https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

Note: People have mentioned lack of critical APIs support missing on Safari 
- https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/5238#issuecomment-647805765
- https://github.com/refined-github/refined-github/issues/14#issuecomment-713975918

Once I figure out a way around #66 (as that is now a more pressing issue at the moment for new extensions) I will spend some time on this issue too maybe around the weekends as I am engaged on weekdays with a full time job.

Like always, contributions & support are welcome from anyone.

cc: @MerrickClark @fregante

**Comment by lsmith77** [comment]
@anaclumos why did you close the issue?
