### ISSUE TITLE
How to use react devtools?

### ISSUE THREAD

**Issue by Gvozd** [abhijithvijayan/web-extension-starter#51]
In сhrome, extensions not working on extension page(e.g. options.html)
And i dont know a way to make them work

How do you use React Devtools?
Is there some easy way?

I'm trying to use react-devtools-inline for now, and I will share the solution later, if there are no simpler/convenient solutions

**Comment by abhijithvijayan** [comment]
What do you mean by extensions are not working on options page?

**Comment by Gvozd** [comment]
In Chrome
1. I install react devtools extension https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi
2. Go to chrome-extension://poejihmdinohpgnbcpfidehmnnakjkfn/options.html of developed extension
3. F12 - has now react devtool tabs in chrome devtools

**Comment by Gvozd** [comment]
@abhijithvijayan
Do you have any ideas how to use react devtools for debug plugin?

**Comment by abhijithvijayan** [comment]
Let me check it out

**Comment by abhijithvijayan** [comment]
@Gvozd I have looked into the issue and noticed that it is due to restrictions put by the browser.

But you can take a look at this [solution](https://stackoverflow.com/questions/34540491/when-developing-chrome-extension-chrome-react-devtools-doesnt-show-up) to get it working

**Comment by abhijithvijayan** [comment]
Solution:

> ref: https://www.npmjs.com/package/react-devtools#usage-with-react-dom

- Instal react-devtools 
	```
	# globally
	yarn global add react-devtools

	# or locally
	yarn add --dev react-devtools
	```
- Add script tag to `popup.html` or `options.html`
	```
    <!doctype html>
    <html lang="en">
    <head>
       <script src="http://localhost:8097"></script>
    ...
   ```
- Update `manifest.json`
	```
    # remove
    "content_security_policy": "script-src 'self'; object-src 'self'",
    
    # add these two lines instead
    "__dev__content_security_policy": "script-src 'self' http://localhost:8097; object-src 'self'",
    "__prod__content_security_policy": "script-src 'self'; object-src 'self'",
    ```
- Run `react-devtools` in the console
  ```
  # or if you are installing locally
  # add this script to package.json
  
  "scripts": {
    "react-devtools": "react-devtools"
  }

  # and run
  yarn react-devtools
 ```
- Launch chrome extension in browser(restart extension `chrome://extensions` if already running)
- Voila!

**Comment by abhijithvijayan** [comment]
Closing for now. feel free to reopen if issue still persist.

**Comment by abhijithvijayan** [comment]
@Gvozd did it work for you?

**Comment by Gvozd** [comment]
@abhijithvijayan 
yes, it works, but not fully
It lacks an item selection button on the page, and navigation to the source code of the component
![image](https://user-images.githubusercontent.com/1365584/99199478-7bd1b380-27b0-11eb-9a83-9b9a96fe5735.png)

I experimented with the `react-devtools-inline`, and opening it in another tab
In this case "select an element" worked
But this module requierd experimental versions of react/react-dom
But this problem can be solved

But it is still less convenient than debugging with an extension, as for regular sites.

**Comment by abhijithvijayan** [comment]
updated the answer here to use a custom webpack plugin i wrote now. works fine in my project.
