### ISSUE TITLE
CRX_REQUIRD_PROOF_MISSING when trying to install the generated .crx on chrome

### ISSUE THREAD

**Issue by ChildishGiant** [abhijithvijayan/web-extension-starter#65]
![image](https://user-images.githubusercontent.com/13716824/118414827-b99b9000-b69e-11eb-8feb-cffbd7835586.png)

I can install it on new edge (chromium) without this issue.

**Comment by abhijithvijayan** [comment]
Try using zip instead.

I will look into this issue. I think latest chromes have this issue

https://stackoverflow.com/questions/56930454/chrome-extension-throws-crx-file-error-crx-requird-proof-missing

**Comment by abhijithvijayan** [comment]
By the way, the webpack setup only builds extension in crx for opera, it is now building into zip for chrome

**Comment by ChildishGiant** [comment]
It's probably worth noting that I'm using the master branch

**Comment by abhijithvijayan** [comment]
Even still, the [webpack config](https://github.com/abhijithvijayan/web-extension-starter/blob/master/webpack.config.js) builds zip for chrome.
