### ISSUE TITLE
fsevent is incompatible with this module, build skipped.

### ISSUE THREAD

**Issue by zava810** [abhijithvijayan/web-extension-starter#67]
yarn install # build is getting skipped in linux mint 20
[yn0062](https://yarnpkg.com/advanced/error-codes#yn0062---incompatible_os)
The platform linux is incompatible with this module, build skipped.

**Comment by abhijithvijayan** [comment]
@zava810 i have bumped dependencies for `react-typescript` branch.

try with the latest version of the branch and see if it works

**Comment by zava810** [comment]
1) eslint-config-airbnb-typescript@npm:8.0.2 [92137] doesn't provide eslint-plugin-react-hooks (pf358d), requested by eslint-config-airbnb
2) YN0062 : fsevents@patch:fsevents .... linux is incompatible with this module, build skipped
in linux it is compatible with both typescript/javascript release.

**Comment by abhijithvijayan** [comment]
stale. closing.
