### ISSUE TITLE
How to import jsx file in ContentScript?

### ISSUE THREAD

**Issue by linonetwo** [abhijithvijayan/web-extension-starter#71]
I get

```
ERROR in ./src/ContentScript/index.ts
Module not found: Error: Can't resolve './FloatingPanel' in 'xxxxx/ContentScript'
```

<img width="225" alt="截屏2021-06-25 下午8 48 40" src="https://user-images.githubusercontent.com/3746270/123427060-ba590780-d5f6-11eb-8547-3c4a0334dd5e.png">

/ContentScript/index.ts
```ts
import './FloatingPanel';

export {};
```

/ContentScript/FloatingPanel/index.jsx
```ts
import * as React from 'react';
import ReactDOM from 'react-dom';

function FloatingPanel() {
  return <div>aaaa</div>;
}

const mountPointID = 'gamification-floating-ui-root';
document.body.insertAdjacentHTML('afterend', `<div id="${mountPointID}" />`);
ReactDOM.render(<FloatingPanel />, document.querySelector(`#${mountPointID}`));

```

This will not work.

So, How to render a React widget right into the webpage?

**Comment by abhijithvijayan** [comment]
i will investigate this soon

**Comment by abhijithvijayan** [comment]
Btw you are not exporting anything inside FloatingPanel/index.tsx

**Comment by linonetwo** [comment]
I guess that is why you `export {};` in the index.ts

Oh, I tried out, but after I add `export {};` to `index.tsx` it still can't be resolved...

**Comment by abhijithvijayan** [comment]
You are using `react-javascript` branch I presume

**Comment by abhijithvijayan** [comment]
I will check it out later.

**Comment by linonetwo** [comment]
Oh， wow, you point out the thing, it should be named `index.tsx`

Actually I'm using React + TypeScript branch, so this solves my problem, than you for this quick help!

**Comment by linonetwo** [comment]
This starter works pretty great, thank you for making this. I've followed you in Github now.

**Comment by abhijithvijayan** [comment]
Cool. Glad to know repo helped.
