### ISSUE TITLE
How to add CSS Modules into ContentScript?

### ISSUE THREAD

**Issue by arnaumanyosa** [abhijithvijayan/web-extension-starter#75]
Sorry if it's not the place, probably it's not an issue, but I don't know where to ask.

I use React with Typescript. In ContentScript I load a custom component which is in `source/shared/components/MyComponent/MyComponent.tsx`

and I create a Scss for it: `source/shared/components/MyComponent/MyComponent.scss`

I notice that the styling is added in `extension/firefox/css/contentScript.css` when it's built, but It's not loaded when I run my browser extension.

It's possible to make it work or only inline CSS can work?

Thank you!

**Comment by abhijithvijayan** [comment]
resolved?

**Comment by arnaumanyosa** [comment]
Yes, resolved. I close the issue. Thanks!

**Comment by nemanjam** [comment]
I also cant load styles for content script, what is the solution?
