### ISSUE TITLE
Unsure how to compile new scss files to put in.

### ISSUE THREAD

**Issue by velocinator** [abhijithvijayan/web-extension-starter#81]
I'm using the master branch (I'm unsure how far behind this branch is, but I haven't been able to add any new SCSS files to my project.

**Comment by abhijithvijayan** [comment]
all the branches are up-to-date in their own way. what is the issue you are facing? i checked the scss webpack config across `master` & `react-typescript` branch and both are same so it should work fine. there are already some global scss files uses in `master` branch
