### ISSUE TITLE
Node-sass is deprecated

### ISSUE THREAD

**Issue by arnaumanyosa** [abhijithvijayan/web-extension-starter#86]
> Warning: [LibSass and Node Sass are deprecated](https://sass-lang.com/blog/libsass-is-deprecated). While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto [Dart Sass](https://sass-lang.com/dart-sass).

Move to sass package.

Would be any issue on webpack, etc?

**Comment by arnaumanyosa** [comment]
Apparently by removing `node-sass` and installing `sass` is enough and it everything works as expected.

https://stackoverflow.com/questions/63943756/replace-node-sass-with-dart-sass-in-create-react-app-v3-x

**Comment by Egor-Koldasov** [comment]
Why the issue is closed though? package.json still has the deprecated node-sass. I wasn't even able to run the project until I replaced the dependency in my fork.

**Comment by arnaumanyosa** [comment]
@Egor-Koldasov Good question, probably I was busy at that time or something and just added the info. 

@abhijithvijayan Here is a PR to fix this https://github.com/abhijithvijayan/web-extension-starter/pull/94

**Comment by abhijithvijayan** [comment]
this is resolved.
