### ISSUE TITLE
The overleaf pdf appear on top of the textarea and hide it

### ISSUE THREAD

**Issue by lr72** [abhijithvijayan/web-extension-starter#87]
![image](https://user-images.githubusercontent.com/8665420/162566620-cc58672c-b30f-4bd0-a10d-1cc1986b1b77.png)

**Comment by Birdi7** [comment]
Hello! I have the similar problem. I think overleaf made a release some time ago, and this issue appreared

**Comment by abhijithvijayan** [comment]
this isnt related to any extensions on store at all.
