### ISSUE TITLE
Grammarly pop-up window blocking our review

### ISSUE THREAD

**Issue by alburidy** [abhijithvijayan/web-extension-starter#95]
First of all,

THANK YOU SO MUCH FOR THIS AMAZING TOOL!

I have only one issue with it though: 
Grammarly pop-up window is blocking our review. Is it possible to minimize it while writing?

<img width="960" alt="95" src="https://user-images.githubusercontent.com/70868579/186092499-196ba8b0-2312-40d0-ac8a-5aaee0bef76f.png">

**Comment by abhijith-vijayan** [comment]
this issue is not related to this project. please consider reporting it to the appropriate developers.

**Comment by abhijithvijayan** [comment]
This issue is not related to this project. Please report it to the overleaf extension you are using. Probably they use this project to build their extension but this project is not related to that.
